# Generated by Django 2.2.1 on 2020-05-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0005_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='state_id',
            new_name='state',
        ),
    ]
