# Generated by Django 2.2.1 on 2020-05-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0006_auto_20200530_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
