# Generated by Django 2.2.1 on 2020-06-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_portal', '0008_auto_20200530_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transition',
            old_name='transition',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(default='Backlog', on_delete=django.db.models.deletion.CASCADE, to='project_management_portal.State'),
        ),
        migrations.RemoveField(
            model_name='transition',
            name='from_state',
        ),
        migrations.AddField(
            model_name='transition',
            name='from_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='present_state', to='project_management_portal.State'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='transition',
            name='to_state',
        ),
        migrations.AddField(
            model_name='transition',
            name='to_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management_portal.State'),
            preserve_default=False,
        ),
    ]
